quest-bot-memcached:
  image: phpdockerio/memcached:latest
  container_name: quest-bot-memcached

quest-bot-mysql:
  image: mysql:5.7
  container_name: quest-bot-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123
    - MYSQL_DATABASE=quest-bot
    - MYSQL_USER=123
    - MYSQL_PASSWORD=123
  ports:
   - "8036:3306"

quest-bot-webserver:
  image: phpdockerio/nginx:latest
  container_name: quest-bot-webserver
  volumes:
      - ../src:/var/www/quest-bot
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8001:80"
  links:
   - quest-bot-php-fpm

quest-bot-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: quest-bot-php-fpm
  volumes:
    - ../src:/var/www/quest-bot
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - quest-bot-memcached
    - quest-bot-mysql
